fix: another attempt to fix EOF error

diff --git a/.github/workflows/chan-ko-website-deploy.yml b/.github/workflows/chan-ko-website-deploy.yml
--- a/.github/workflows/chan-ko-website-deploy.yml
+++ b/.github/workflows/chan-ko-website-deploy.yml
@@ -102,30 +102,43 @@ jobs:
           sudo chown -R www-data:www-data /var/www/html
 
           echo "Updating Nginx config to force HTTPS"
-          sudo tee /etc/nginx/sites-available/default > /dev/null << EOF
-          server {
-            listen 80;
-            server_name '"$DOMAIN"';
-            return 301 https://\$server_name\$request_uri;
-          }
+          sudo bash -c "cat > /etc/nginx/sites-available/default << EOL
+server {
+    listen 80;
+    server_name $DOMAIN;
+    return 301 https://\$server_name\$request_uri;
+}
 
-          server {
-            listen 443 ssl;
-            server_name '"$DOMAIN"';
+server {
+    listen 443 ssl;
+    server_name $DOMAIN;
 
-            ssl_certificate /etc/letsencrypt/live/'"$DOMAIN"'/fullchain.pem;
-            ssl_certificate_key /etc/letsencrypt/live/'"$DOMAIN"'/privkey.pem;
+    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
+    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
 
-            root /var/www/html;
-            index index.html;
+    root /var/www/html;
+    index index.html;
 
-            location / {
-                try_files \$uri \$uri/ =404;
-            }
-          }
-          EOF
+    location / {
+        try_files \$uri \$uri/ =404;
+    }
+}
+EOL"
 
-          sudo nginx -t && sudo systemctl restart nginx
+          echo "Nginx configuration created. Checking syntax..."
+          sudo nginx -t
+
+          if [ $? -eq 0 ]; then
+            echo "Nginx syntax is correct. Restarting Nginx..."
+            sudo systemctl restart nginx
+          else
+            echo "Nginx syntax check failed. Printing configuration file:"
+            cat /etc/nginx/sites-available/default
+            exit 1
+          fi
+
+          echo "Nginx status:"
+          sudo systemctl status nginx
         '
 
         gcloud compute ssh ${{ secrets.CHANKO_WEBSITE_GCE_INSTANCE_NAME }} --zone=${{ secrets.CHANKO_WEBSITE_GCE_ZONE }} --command='sudo mkdir -p /var/www/html && sudo chown -R $(whoami):$(whoami) /var/www/html'
